apiVersion: v1
kind: Namespace
metadata:
  name: couchdb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /mnt/ZfsMedia/kubernetes/
    server: 192.168.123.30

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: couchdb
  name: pvc0003
spec:
  accessModes:
  - ReadWriteOnce    
  resources:
     requests:
       storage: 20Gi

---
kind: Service
apiVersion: v1
metadata:
  namespace: couchdb
  name: couchdb
  labels:
    app: couchdb
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.40
  ports:
  - name: couchdb
    protocol: TCP
    port: 5984
    targetPort: 5984
  selector:
    app: couchdb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: couchdb
  labels:
    app: couchdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: couchdb
  serviceName: couchdb
  template:
    metadata:
      labels:
        app: couchdb
        name: couchdb
    spec:
      containers:
      - name: couchdb
        image: treehouses/couchdb
        imagePullPolicy: Always
        ports:
        - name: couchdb
          protocol: TCP
          containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: pass
        volumeMounts:
        - name: couchdb
          mountPath: /opt/couchdb/data
          subPath: couchdb0
      volumes:
      - name: couchdb
        persistentVolumeClaim:
          claimName: pvc0003