apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
kind: Service
apiVersion: v1
metadata:
  namespace: mysql
  name: mysql
  labels:
    app: mysql
    type: LoadBalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.80
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
        name: mysql
    spec:
      containers:
      - name: mysql
        image: hypriot/rpi-mysql
        imagePullPolicy: Always
        ports:
        - name: mysql
          protocol: TCP
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test